class_names:
  - portrait
  - serial
  - federal_seal
  - signature
  - denomination
  - treasury_seal_federalnote
  - treasury_seal_nonfederalnote

num_images: 250

distance_treshold: 0.06

pos_threshold: 0.1
edge_threshold: 0.05
